add error handlers and constant class with error messages
Vasiliy566/annotator pull request #1
Opened 2020-02-10 20:31 UTC by Vasiliy566

next step: 
add test in ApplicationTest.kt
add Documentation
replace functions those require long time with fast functions using tbi-index
*not answer "null" when annotation is not found ( answer "not found" or null message)
P.S.
Приношу извинения за такую задержку
Невнимательно прочитал задание, думал что нужно искать данные в файле 42.tsv варианты в базе типа Clinvar и пытался разобраться, как без другого аннотатора самому искать их в базе, а когда разобрался - не нашел описаний и понял, что делаю все не так

2020-02-12 14:20 UTC, nopechucktesta reviewed
Предлагаю поближе познакомиться с таким _объектом_ в Kotlin как **object** (попутно разобравшись во взаимоотношениях классов и их **companion object**s). Очень похоже, что некоторые ваши идеи лучше было бы выразить именно с помощью него.
И хотелось бы, чтобы чуть больше внимания было уделено оформлению кода и возникающим в ИДЕЕ (вы же в ней работаете?) warnings (не зря же ИДЕЯ является таким мощным инструментом работы с кодом). Если это сделать осознанно, то мы сможем избежать процентов восемьдесят вопросов по вашему коду.

2020-02-12 20:43 UTC, AleksandrSl requested changes

2020-02-12 20:43 UTC, AleksandrSl commented on src/Application.kt
> +                    var raw = call.parameters.get("vcf")!!
А по какой причине почти повсеместно используется `var`?

2020-02-12 20:43 UTC, AleksandrSl commented on src/Application.kt
>              get("/getAnnotation"){
Метод (GET) говорит нам достаточно, не стоит дублировать его в эндпойнте

2020-02-12 20:43 UTC, AleksandrSl commented on src/Constants.kt
> +    companion object {
А почему мы решили воспользоваться `companion object`?
Если принять, что мы действительно захотели собрать эти "константы" в одном месте, то стоит посмотреть что такое `object`  в Kotlin

2020-02-12 20:43 UTC, AleksandrSl commented on src/Constants.kt
> +            "No vcf parameter provided.\nexpected \"?vcf="+ VCF_FORMAT
В котлине есть шаблонные строки - https://kotlinlang.org/docs/reference/basic-syntax.html#using-string-templates

2020-02-12 20:43 UTC, AleksandrSl commented on src/Constants.kt
> +        fun getEmptyParameters():String {
В чем преимущество таких функций над обычными геттерами для свойств, которые генерируются автоматически? https://kotlinlang.org/docs/reference/properties.html#properties-and-fields

2020-02-17 12:32 UTC, Vasiliy566 commented on src/Application.kt
> +                    var raw = call.parameters.get("vcf")!!
Поправил, где было возможно

2020-02-17 12:32 UTC, Vasiliy566 commented on src/Application.kt
>              get("/getAnnotation"){
поправил

2020-02-17 12:53 UTC, Vasiliy566 commented on src/Constants.kt
> +    companion object {
Не нашел рекомендованного способа хранить константы в котлине, использовал метод, указанный здесь
https://blog.egorand.me/where-do-i-put-my-constants-in-kotlin/

2020-02-17 12:56 UTC, Vasiliy566 commented on src/Constants.kt
> +        fun getEmptyParameters():String {
В том, что можно сделать поля класса с константами приватными
*Поправил

2020-02-19 12:16 UTC, Vasiliy566 commented on src/Constants.kt
> +            "No vcf parameter provided.\nexpected \"?vcf="+ VCF_FORMAT
Поправил

2020-02-24 21:30 UTC, Vasiliy566 reviewed
Исправил

2020-02-25 19:11 UTC, AleksandrSl approved these changes

2020-02-27 18:10 UTC, nopechucktesta approved these changes

2020-03-07 08:55 UTC, merged