add unit tests and refactor requests
Vasiliy566/annotator pull request #2
Opened 2020-02-11 08:20 UTC by Vasiliy566

add request answers to own class RequestHandler

2020-02-12 14:43 UTC, nopechucktesta reviewed
Конечно, хотелось бы чуть более _гранулярной_ работы в рамках Pull request. Никто не ограничивает вас в их количестве, и хорошей практикой является создание "атомарных" PR, отвечающих за добавление (обновление/удаление) _одной_ feature. В рамках, например, данного PR можно наблюдать как минимум три таких (_самостоятельных_) feature:
- добавление Unit-тестов (что в общем случае редко является "атомарным действием", ведь можно такую задачу, например, разбить на добавление Unit-тестов к отдельным частям системы);
- добавление конфигурации настройки GitHub Workflows;
- рефакторинг кода, отвечающего за обработку входящих запросов (на получение аннотации).

Это (небольшой "атомарный" PR) как минимум позволяет облегчить задачу вашим коллегам, осуществляющих review. В более широком смысле это позволяет лучше структурировать процесс разработки (откуда может вытекать масса частных вещей, среди которых, например, могут возникать: ослабление связей между компонентами системы, упрощение схем тестирования системы, возможность "инкрементального" добавления нового функционала, то есть без изменения старого, и проч.).

Как вы, кстати, оцениваете свой уровень владения таким инструментом как Git?

2020-02-12 20:50 UTC, AleksandrSl requested changes

2020-02-12 20:50 UTC, AleksandrSl commented on src/VcfHandler.kt
>  data class SingleVariant(
Стоит внимательнее посмотреть что значит слово data перед классом, можно будет писать гораздо меньше кода, и он будет написан надежнее - https://kotlinlang.org/docs/reference/data-classes.html

2020-02-12 20:50 UTC, AleksandrSl commented on src/VcfHandler.kt
> +    fun equals(other: VariatnInfo): Boolean {
Если принять, что нам нужен этот метод (спойлер - нет: https://kotlinlang.org/docs/reference/data-classes.html) ,
то не стоит писать код типа 
```
if true:
    return true
else:
    return false
```

всегда есть просто `return <boolean_expression>`

2020-02-12 20:50 UTC, AleksandrSl commented on src/VcfHandler.kt
>  data class VariatnInfo(
Опечатка в названии, IDEA должна вроде такое подчеркивать, она плохого редко советует

2020-02-12 20:50 UTC, AleksandrSl commented on src/RequestHandler.kt
> +    companion object {
Чем все же так вызвана любовь к companion objectам?

2020-02-12 20:50 UTC, AleksandrSl commented on test/ApplicationTest.kt
> +            assertEquals(VcfHandler.inputParse(rawTestData[i]), parsedTestData[i])
А что конкретно тестируют 4 случая? Кажется, что они все тестируют одно и тоже, и можно вместо 4 тест кейсов один оставить?

2020-02-17 12:37 UTC, Vasiliy566 commented on test/ApplicationTest.kt
> +            assertEquals(VcfHandler.inputParse(rawTestData[i]), parsedTestData[i])
Тестируют различные поля, так как поля имеют разный тип. Могу отставить только два случая различных типов данных

2020-02-17 16:39 UTC, Vasiliy566 commented on src/VcfHandler.kt
> +    fun equals(other: VariatnInfo): Boolean {
Убрал метод

2020-02-17 16:39 UTC, Vasiliy566 commented on src/VcfHandler.kt
>  data class VariatnInfo(
Исправил все warning от Идеи

2020-02-17 16:40 UTC, Vasiliy566 commented on src/RequestHandler.kt
> +    companion object {
Прочитал, что это аналог static в Java

2020-02-19 08:39 UTC, AleksandrSl commented on test/ApplicationTest.kt
> +            assertEquals(VcfHandler.inputParse(rawTestData[i]), parsedTestData[i])
В каком смысле различные поля? Мы парсим 4 одинаковых валидных варианта.

2020-02-19 13:06 UTC, Vasiliy566 commented on test/ApplicationTest.kt
> +            assertEquals(VcfHandler.inputParse(rawTestData[i]), parsedTestData[i])
Думал это по поводу тестов выше. 
Исправил в последнем коммите

2020-02-21 06:07 UTC, Vasiliy566 commented on src/VcfHandler.kt
>  data class SingleVariant(
Прочитал, что data-класс в Kotlin'е  data class что то типа structure в c++, служит для хранения, подробнее ответил по почте

2020-02-24 21:33 UTC, Vasiliy566 commented on src/RequestHandler.kt
> +    companion object {
Исправил, вместо добавления функций, которые хочется сделать static, в companion object, вынес их отдельно

2020-02-24 21:33 UTC, Vasiliy566 reviewed
Исправлено

2020-02-25 19:14 UTC, AleksandrSl approved these changes

2020-02-27 18:09 UTC, nopechucktesta approved these changes

2020-03-07 08:53 UTC, merged