Tabix
Vasiliy566/annotator pull request #4
Opened 2020-02-18 23:26 UTC by Vasiliy566

Добавил метод getFast, который определяет по индекс-файлу аннотацию

2020-02-19 08:20 UTC, AleksandrSl commented on src/Application.kt
> +    val server = embeddedServer(Netty, port = 8089) {
А нам для поддержки tabix потребовалось поменять порт?

2020-02-19 13:19 UTC, Vasiliy566 commented on src/Application.kt
> +    val server = embeddedServer(Netty, port = 8089) {
Поменял на дефолтный во всех ветках

2020-02-21 14:24 UTC, nopechucktesta requested changes
А что будет, если в _runtime_ не окажется `tabix`?

2020-02-24 21:28 UTC, Vasiliy566 reviewed
Добавил проверку на наличие tabix, так же можно запускать долгую версию, но не думаю, что такой сервис имеет смысл использовать, тем более что установка tabix занимает мало времени

2020-02-24 21:29 UTC, Vasiliy566 reviewed
Исправил в последнем коммите

2020-02-25 19:16 UTC, AleksandrSl approved these changes

2020-02-25 20:06 UTC, nopechucktesta approved these changes

2020-02-25 20:08 UTC, nopechucktesta commented on src/Application.kt
> +        print("tabix not found, install it befor server running")
Оригинальный подход. Условие хоть и является, казалось бы, чересчур сильным, но задачу необходимую выполняет.

2020-02-27 21:26 UTC, merged